# Generated by Django 2.0.3 on 2020-05-08 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerPlatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('price_large', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('price_small', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('price_large', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('price_small', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('price_large', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('price_small', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('number_of_toppings', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('price_large', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('price_small', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('price_large', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('price_small', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubAddition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('price_large', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('price_small', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.PizzaType'),
        ),
        migrations.AlterUniqueTogether(
            name='pizza',
            unique_together={('name', 'pizza_type')},
        ),
    ]
