# Generated by Django 2.0.3 on 2020-05-07 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200507_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinnerplatter',
            old_name='dp_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sub',
            old_name='sub_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='dinnerplatter',
            unique_together={('name', 'size')},
        ),
        migrations.AlterUniqueTogether(
            name='sub',
            unique_together={('name', 'size')},
        ),
    ]
