# Generated by Django 2.0.3 on 2020-05-12 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200512_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AddType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='adds',
            field=models.ManyToManyField(blank=True, to='orders.SubAddition'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='tops',
            field=models.ManyToManyField(blank=True, to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='addition',
            name='add_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.AddType'),
        ),
    ]
