# Generated by Django 2.0.3 on 2020-05-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200512_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addition',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='addition',
            unique_together={('name', 'add_type')},
        ),
    ]
