# Generated by Django 2.0.3 on 2020-05-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_purchase_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='notes',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
