# Generated by Django 2.0.3 on 2020-05-15 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200514_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtype',
            name='parent_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.ItemType'),
        ),
    ]
