# Generated by Django 2.0.3 on 2020-05-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_addtype_parent_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtype',
            name='parent_type',
        ),
        migrations.AddField(
            model_name='addtype',
            name='parent_type',
            field=models.ManyToManyField(related_name='add_types', to='orders.ItemType'),
        ),
    ]
