# Generated by Django 2.0.3 on 2020-05-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200515_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
