# Generated by Django 2.0.3 on 2020-05-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_purchase_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='qwe',
            field=models.CharField(default='', max_length=128),
        ),
    ]
