# Generated by Django 2.0.3 on 2020-05-15 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_purchase_qwe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='qwe',
        ),
    ]
