# Generated by Django 2.0.3 on 2020-05-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_remove_purchase_qwe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='order',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
