# Generated by Django 2.0.3 on 2020-05-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20200516_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pending',
        ),
        migrations.AddField(
            model_name='order',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
